### ISSUE TITLE
[レビュー申請]コミュニティガイドライン

### ISSUE THREAD

**Issue by hikalium** [osdev-jp/osdev-jp.github.io#3]
申請者: hikalium
対象: https://github.com/osdev-jp/osdev-jp.github.io/wiki/Guidlines
レビューフローのテストも兼ねて、レビューをお願いします！

**Comment by liva** [comment]
> オープンコミュニティには、申請の上誰でも所属することが可能です。

申請というのは、アカウント作成とかそういった類の物になるのでしょうか？

> オープンコミュニティメンバーができること

チャットルームがあっても良いかもしれないと思いました。

> Tips: 需要のある内容に関する記事のほうがレビューを通りやすくなります！事前にコミュニティ内で需要調査をしておくとよいでしょう。

コミュニティ内で需要調査しても、オープンコミュニティ内の需要とコアメンバー内の需要が一致しない場合があるんですよね。
オープンコミュニティメンバーが、どうやってコアメンバー内の需要を調査すれば良いのか、仕組みづくりをする必要がありそうです。

うーん、需要調査用のチャットルームを作れば良いのかな？




他はLGTMです！

**Comment by uchan-nos** [comment]
ロックしてみました。Writeアクセスがある人以外は書き込めないはず！

**Comment by hikalium** [comment]
@liva 
そうですね、「申請」とは何かもう少し具体的に書くことにします。
「GitHubのアカウント作成の上、コラボレーター申請をすることで」でよいでしょうか？

チャットに関して、
コミュニティメンバーなら誰でもSlackとCybozuLive両方利用できるということでOKでしょうか。
もちろん、コアメンバー用の秘密チャンネル(Slackの場合)を両方に用意することもします。

Tipsについて
コアメンバー内の需要調査の件ですが、オープンコミュニティ全体のチャットルームで「需要調査」のようなチャンネルを作成し、そこに投げることでよいと思います。別にコアメンバーに限る必要もないし、コアメンバーが誰だかは公開される（はず）なので、直接指名したりすることもできますし。

どうでしょうか？
ポリシーの方に修正を加えたらまたコメントします。

**Comment by uchan-nos** [comment]
申請については、コラボレータではなくTeamに属させる方針になりそうです。コラボレータはリポジトリ固有、Teamはすべてのリポジトリ共通にできて便利だからです。

CybozuLiveはいらないかもしれません。
なぜなら、GitHub issuesでもロックさえしてしまえば、Write権限のある人（つまり、Teamに属している人）だけが書き込める状態になり、レビューができるからです。

チャットはコミュニティメンバーならだれでも書き込めていいと思います。需要調査チャンネルが機能するかはわからないですね。皆ちゃんとチェックするでしょうか？雑談チャンネルで聞いてみるのが効果的かもしれないなあと思っています。

**Comment by liva** [comment]
slackが整備されたので、概ね良いと思います。

需要調査については実際にやってみない事にはわからないですよね。であればひとまず雑談チャンネルで運用するという形で良いと思います。

**Comment by uchan-nos** [comment]
@hikalium 

記事の中身は素晴らしいです！
ちょっと見出しを直すとよりよくなると思いました。

「オープンコミュニティ」と「コアメンバー」が対になる見出しなのだと思います。片方がコミュニティで片方がメンバーで、名詞の種類がそろってないのでそろえてください。

それから `##` 見出しの後の本文が 1 文しかないと、次の見出しと間隔が空かないので不格好に見えます。もうちょっと工夫できませんか？

> WordPress
「WordPress」は単なる一つの実現手段で、抽象化すると「GitHub Wiki ではない、コアメンバー専用の媒体」ですよね。将来 WordPress をやめることも十分あり得ます。

したがって、記事では「コアメンバー用メディア」（用語は適当）と書いて、最後に「現在、コアメンバー用メディアとして WordPress （osdevjp.wordpress.com）を利用しています。」みたいに書く方が良いと思います。

**Comment by hikalium** [comment]
レビューを参考に変更を施しました！

@uchan-nos 
「コアメンバー用メディア」という表記ですが、あまりにも冗長になってしまうため、WordPressのままにしました。将来的にWordPress以外のメディアになった場合は、適宜ガイドラインの方を修正するということでどうでしょうか？

**Comment by uchan-nos** [comment]
@hikalium WordPressをそのままとするのは、確かにそれでいい気がしてきました。具体的なので分かりやすいです。

一点、誤字報告です。
> コアメンバーの人数が減少した祭の例外条項
際、です。

**Comment by hikalium** [comment]
@uchan-nos typo修正しました…。
これで大丈夫でしょうか？（絵文字で+1, -1お願いします！）
